package Integration

@Library('shared_library@dev') _

pipeline{

    agent { node { label 'master' } }
    stages {

        stage('Send slack correct notification as script'){

            steps {
                script{
                    slack.successBuild()
                    slack.successBuild('')
                    slack.successBuild(null)
                    slack.successBuild('#jenkins_test')

                    slack.failedBuild()
                    slack.failedBuild('')
                    slack.failedBuild(null)
                    slack.failedBuild('#jenkins_test')

                    slack.failedTests()
                    slack.failedTests('')
                    slack.failedTests(null)
                    slack.failedTests('#jenkins_test')
                }


                echo "Some"
            }

        }

        stage('Send slack correct notification as global'){

            steps {

                    slackSuccessBuild()
                    slackSuccessBuild('')
                    slackSuccessBuild(null)
                    slackSuccessBuild('#jenkins_test')

                    slackFailedBuild()
                    slackFailedBuild('')
                    slackFailedBuild(null)
                    slackFailedBuild('#jenkins_test')

                    slackFailedTests()
                    slackFailedTests('')
                    slackFailedTests(null)
                    slackFailedTests('#jenkins_test')

            }

        }

    }

}
